### ISSUE TITLE
Allow re-encrypting entire store

### ISSUE THREAD

**Issue by Gigahawk** [geluk/pass-winmenu#105]
On v1.13, it seems that I can only re-encrypt a specific folder in the store, but not the whole store itself.

[This comment](https://github.com/geluk/pass-winmenu/issues/91#issuecomment-885776691) from #91 mentions that at some point the menu option would re-encrypt the entire store, I think it would be helpful to have this as an option, or perhaps an option that would accept some sort of glob/list of paths to re-encrypt.

**Comment by lcnittl** [comment]
I think this is already possible: Click on task bar icon, then `More Actions`>`Re-encrypt Password Store`

![image](https://user-images.githubusercontent.com/23134999/171995739-e20f42be-cf17-40cb-83c6-c153f97e03cb.png)

**Comment by Gigahawk** [comment]
If you click Yes, you get the following dialog where you can only pick a specific folder to encrypt, not the whole store:
![image](https://user-images.githubusercontent.com/10356230/172267745-ff1d7bbd-8750-4f5d-926c-c83b6bc7524f.png)

**Comment by lcnittl** [comment]
Ah, that's right! The text in that confirmation windows was so promising that I did not proceed to re-encrypt, sorry about that!

Then +1 from me -- would be a handy feature.

**Comment by geluk** [comment]
Hi @Gigahawk, I looked into this, it seems to be due to an oversight in the way the directory tree is generated. I'll fix this issue in the next release. For now, you can work around it by placing a dummy file ending with `.gpg` in the root of your password store. You will then see an entry at the top of the list that lets you re-encrypt the entire store:

![image](https://user-images.githubusercontent.com/1516985/173252415-467c1284-8822-459c-a415-bd85d8624d25.png)

**Comment by geluk** [comment]
Implemented in [v1.13.1](https://github.com/geluk/pass-winmenu/releases/tag/v1.13.1).
