### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by ghost** [geluk/pass-winmenu#113]
Hello, is there a translation to non English language available or planed?

**Comment by geluk** [comment]
Hi @basti12203, I am not currently planning to implement any translations as I would have to rely on the community to provide them, and I don't think the project is big enough to be able to support this. Since pass-winmenu has a fairly minimal surface for user interaction, I also do not think translation provides much of a benefit (but feel free to argue on the contrary here).

**Comment by Cesar0106** [comment]
I would like to translate the instructions to brazilian portuguese, would you accept it?
