### ISSUE TITLE
Implement fuzzy search

### ISSUE THREAD

**Issue by akriese** [geluk/pass-winmenu#115]
I am using `pass` on mutliple different systems and in different browsers. A thing that I am currently missing in `pass-winmenu` compared to other plugins/GUIs is fuzzy searching my URLs. I want to be able to effectively filter my collection by selected substrings that I know are in the desired password path/url.
Could something like [FuzzySharp](https://github.com/JakeBayer/FuzzySharp) be leveraged to make fuzzy finding possible without much effort? Glad to hear about what you think about this suggestion :)

**Comment by geluk** [comment]
I definitely think the search functionality could be better. You can search for multiple substrings by separating them with a space, but there is no fuzzy search, abbreviation search, etc.

It hasn't really been a priority for me since the way it works right now is fine for me, but it is definitely possible to improve this. Unfortunately it looks like FuzzySharp has not seen updates in the past 2.5 years, so I'm hesitant about adding it as a dependency, but depending on what search features you're interested in, it may not be too difficult to add those manually. Are there any specific features you'd like to see?

**Comment by akriese** [comment]
I didn't know about using space. That definitely helps already! In case I ever feel the need for fuzzy search, I'll come back to this issue. You can close this if nobody else is interested in this feature.

**Comment by akriese** [comment]
Also, how about mentioning the <space> usage in the Usage section of the readme?

Something like (addition in _italic_):
## Usage

Bring up the password menu with the keyboard shortcut Ctrl Alt P. The password menu allows you to quickly search through your passwords to find the one you are looking for. Navigate through the results by pressing Tab, and press Enter to decrypt the selected password. _Use spaces between words to search for multiple substrings of the password path to filter more efficiently._

**Comment by willpower232** [comment]
why not open a PR ;-)
