### ISSUE TITLE
[Feature request] Display additional information from the password file in an extra pop-up

### ISSUE THREAD

**Issue by szero** [geluk/pass-winmenu#125]
Hello, so as a user of https://github.com/passff/passff on Linux, you can set extra information in your password files according to scheme below:
```
<the_password>
login: <the_login>
url: <the_url>
<other_inputfield_name>: <inputfield_value>
```

Would be nice if this information would be showed to the user somehow while using this program since remembering all the logins can be cumbersome as well (for now I circumvent this by using the "Edit Password File" to remind myself of the logins) . It could work like that: If the password file has more than one line, show those lines in an additional popup.

**Comment by szero** [comment]
Ok nvm, didn't read through the config file carefully for the first time, was able to get desired functionality of grabbing logins from the password files and pasting it into the input boxes with the following config options adjusted:

```yaml
hotkeys:
    hotkey: 'ctrl alt u'
    action: 'decrypt-password'
    options:
        copy-to-clipboard: true
        type-username: true
        type-password: true

username-detection:
      method: 'regex'
      options:
          regex: '^(user[name]?:|email:|login:)\s*((?<username>.*)[\n\r]+|(?<username>.*))$'
          regex-options:
              ignore-case: true
              multiline: true
              singleline: false

**Comment by geluk** [comment]
One more feature that you can use for other fields:

```
hotkeys:
    hotkey: 'ctrl alt f'
    action: password-field
    options:
        copy-to-clipboard: true
        type: true
```

This will first give you a prompt to select a password, then another prompt to select a field (like `login` or `url` in your example), after which it copies/types the value from the field just like it might type your password.

This is mostly meant for fields that don't contain your username, since the method you described above is more useful for decrypting usernames, since it allows pass-winmenu to enter the username and password together, separated by a tab.
