### ISSUE TITLE
An error occurred in registering the hotkey

### ISSUE THREAD

**Issue by IvanMalison** [geluk/pass-winmenu#45]
I get this message whenever i start pass-winmenu. Not sure how to debug this.

**Comment by IvanMalison** [comment]
Seems that I was getting this message because the password-store directory was empty. Seems like a different error message should pop up, but i guess there is no issue.

**Comment by Baggykiin** [comment]
You're right, that doesn't seem like the right error message indeed. I'll look into it.

**Comment by Baggykiin** [comment]
As far as I can tell this error message does not show up when the password store is empty. Startup with an empty password store works fine, and if you try to decrypt a password, it will warn you that you don't have any passwords yet.

I think what probably happened here is that another instance was still running in the background. When that happens, the new instance won't be able to register the hotkey because it is already in use.
I'm planning on making this error message a bit more detailed to indicate this more clearly.

**Comment by Nanonej** [comment]
Hey!
I had this error too, but can't figure out where is the problem.
I don't know how to debug this too, but I often got problems because my system locale is in Japanese, may be it's related.

**Comment by Baggykiin** [comment]
Make sure you are not running pass-winmenu twice. Otherwise the second instance will fail to register its hotkeys because the first instance already registered them. If that is not the case, you can try to disable all hotkeys (comment them in the configuration file), then re-enable them one by one to find out which one is causing issues. It is possible that the hotkey was already taken by a different application.

**Comment by Nanonej** [comment]
Ok ! Indeed I should have open the config file before as commenting the 'ctrl alt shift p' hotkey solved the problem ...
Thank you !

**Comment by geluk** [comment]
Improved this error message in v1.10 to make it more clear that the hotkey was already taken by another application.
