### ISSUE TITLE
Clipboard cannot delete password automatically

### ISSUE THREAD

**Issue by ydajwz123** [geluk/pass-winmenu#72]
As title.
win+v will show password in the clipboard and it will not be deleted automatically.

**Comment by geluk** [comment]
There is no easy solution to this, unfortunately. There are some technical reasons why deleting items from the clipboard history is currently not supported. I investigated this a bit more, and I found out that there may be a few options to make it work. I'll track that in #74.

---

 The reason it shows the password there is because you have clipboard history enabled, which will remember old passwords even after they're cleared by pass-winmenu. If you can live without it, the easiest solution is to simply disable this feature (`Settings > System > Clipboard > Clipboard history`), but if you use it, that's of course not an option.

If you don't want to disable clipboard history, probably the best solution would be to prevent pass-winmenu from placing passwords on your clipboard, and let it type your passwords into login forms instead. You can do this by editing your hotkey configuration and setting `copy-to-clipboard` to `false`.

**Comment by ydajwz123** [comment]
Thanks for quick reply, Since I use this tool in my personal, it doesn't matter actually.

**Comment by Konfekt** [comment]
There is the [`secret` option](https://github.com/palortoff/wclip/blob/dee2147f3187d555c76161e0d9e8b8a11c1dc472/src/Clipboard.cpp#L27) (used by [wclip](https://github.com/palortoff/wclip/) that hides the clipboard content from many clipboard history tools, like Aceme, Ditto, ..
