### ISSUE TITLE
[Enhancement] Support for OTP extension

### ISSUE THREAD

**Issue by Msouza91** [geluk/pass-winmenu#77]
We could use Ctrl-Meta-Shift-P to invoke the OTP extension, not sure if there is a port of it for windows, but would be quite nice to not have to take the phone to login with 2FA.

**Comment by geluk** [comment]
Glad to hear you like it! I am definitely open to merging it; I think it would be a useful addition to have, and if it's integrated nicely I don't foresee any problems maintaining it. If you're interested in adding this feature, feel free to make a proposal as to how you think it should function. Probably it would make sense to implement a new hotkey action for this, so that anyone interested in this feature can bind it to a hotkey of their choice, but I'm open to hearing your ideas on this.

**Comment by rycwo** [comment]
Scratch that 🤦 it does support it, my otpauth line was just malformed. Sorry about the spam!
