### ISSUE TITLE
when i use two languages keyboard

### ISSUE THREAD

**Issue by ghost** [geluk/pass-winmenu#80]
my english is sucks but hope u understand
my language is korean. so i use two languages keyboard(korean/english keyboard). when i press one key it changes english/korean.
when my keyboard set in korean and ctrl+alt+shift+p(autotype) - select list then it types korean, despite i added my password in english.
when my keyboard set in english it types in english and tho my keyboard set in korean, clipboard option(ctrl+alt+p) is types in english too. only problem with keyboard set in korean + autotype.
is it bug? or only my problem?

**Comment by willpower232** [comment]
Auto type will be using whatever your keyboard is currently set to because it has to actually "press" each letter.

I do not think you will be able to use auto type unless you remember to set the keyboard language first every time.

You can use the clipboard option because that always keeps the real value and does not require any letters to be pressed.

Hope that helps.

**Comment by geluk** [comment]
As @willpower232, mentions, there are a couple limitations to the way pass-winmenu currently handles input. I looked into this a little further, and it turns out that there is a way to simulate keypresses that bypass whichever input method Windows has currently enabled. I've experimented a little bit with this, and it seems to work pretty well in my experience.

@joeykendrick, could you try out the version I've linked below, and check if it resolves your issue?
You can just download it and use it as a drop-in replacement for your current `pass-winmenu.exe`.
https://ci.appveyor.com/api/buildjobs/dg59vpetwtw5vl2y/artifacts/pass-winmenu%2Fbin%2FRelease%2Fpass-winmenu.exe

No matter what your keyboard is set to, this version should input the exact text that you've put into your password file.

**Comment by joeykendrick** [comment]
wow it works for me!
thanks

**Comment by geluk** [comment]
Perfect! I'll include this fix in the next release. Until that's out, you can continue to use the build I linked above.

**Comment by joeykendrick** [comment]
alright!
thank u so much😄

**Comment by geluk** [comment]
Fixed in [v1.12](https://github.com/geluk/pass-winmenu/releases/tag/v1.12).
