### ISSUE TITLE
Can't bind to Win-F1 even after disabling the Win-F1 hotkey

### ISSUE THREAD

**Issue by colemickens** [geluk/pass-winmenu#81]
Is it possible to determine what is conflicting? In Linux, I use Win-F1 to copy pass, Win-F2 to copy totp.

But even after doing this and disabling Win-F1, `pass-winmenu` still fails to start, complaining that the hotkey is in-use. https://endurtech.com/how-to-disable-the-f1-help-key-in-windows-10/

Any suggestions?

**Comment by geluk** [comment]
The problem is that Windows itself registers the `Win-F1` hotkey. The article you linked shows how you can prevent windows from opening the help page when you press the hotkey, but it doesn't actually cause the hotkey to be deregistered. Windows has still registered the hotkey, the only difference is that it now fails to execute the action that's bound to it.

In other words, to get this to work, you'll need to find a way to prevent Windows from registering the hotkey in the first place. I'm not sure if there's a way to achieve this, but to be honest, I have my doubts. Perhaps there's a group policy setting somewhere to disable it.

**Comment by colemickens** [comment]
Thanks for the explanation!
