### ISSUE TITLE
.NET Core 5

### ISSUE THREAD

**Issue by colemickens** [geluk/pass-winmenu#82]
Have you looked at switching to .NET Core 5? I sort of got halfway there just to get VS to cooperate with me.

It looks like it was pretty painless, except the Unit Tests need a bit more attention. Did you have any ideas for this? I don't even know if Xunit is still a thing in .NET Core 5?

This isn't necessarily needed, but it might be nice just to make the onboarding ramp as smooth as possible?

**Comment by geluk** [comment]
I have considered it, but as far as I could tell, it does require people to install the runtime if they don't have it yet, which makes the installation experience a bit less smooth. Right now, any reasonably new version of Windows will have the .NET framework 4.6 or later installed, which means pass-winmenu will work directly out of the box.

That said, I'm not opposed to the idea of upgrading at all, especially since it makes the development experience nicer, which I think is also valuable (more external contributions is a good thing, as far as I'm concerned). I'd say that as soon as .NET 5 has a reasonable installation base, I'm happy to switch to it.

**Comment by geluk** [comment]
Implemented in [v1.14](https://github.com/geluk/pass-winmenu/releases/tag/v1.14).
